### ISSUE TITLE
Add Support for tvOS

### ISSUE THREAD

**Issue by jgainfort** [pmick/RxAVFoundation#10]
I believe its just adding `s.tvos.deployment_target    = '9.0'` to the podspec file but I am not sure. I'm fairly certain iOS and tvOS use the same AVFoundation.

If thats the case Im willing to open a PR.

**Comment by jgainfort** [comment]
For reference RxSwift

https://github.com/ReactiveX/RxSwift/commit/3fe6163451992e005912afab4a3ef73971a30f49

**Comment by asowers1** [comment]
I've had success in other projects following what you mentioned above along with this: http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/

**Comment by asowers1** [comment]
Putting money where mouth is: https://github.com/linkedin/ConsistencyManager-iOS/pull/49

**Comment by pmick** [comment]
Thanks for looking into this guys. I haven't gotten time to get around to opening a pull request myself but should be able to this weekend. I wanted to test the pod file change out with a tvOS project.

**Comment by pmick** [comment]
Going to close this issue. I just pushed 1.2.0 up to cocoapods trunk. Let me know if you two have any issues. @jgainfort @asowers1
