### ISSUE TITLE
Example application could't be compiled because of missing `StatusReporting.swift` file

### ISSUE THREAD

**Issue by iharkatkavets** [pmick/RxAVFoundation#12]
Hi, 

![screen shot 2017-07-21 at 11 59 26 am](https://user-images.githubusercontent.com/1083951/28456805-3fc3729a-6e0c-11e7-8aac-8691d09160c9.png)

I downloaded project as zip file from 'master' branch

**Comment by pmick** [comment]
I should be having CI building the example. I will get this fixed this weekend.
